# Generated by Django 5.0.2 on 2024-02-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mymodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="uploads/"
                    ),
                ),
            ],
        ),
    ]
