# Generated by Django 5.0.2 on 2024-02-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customeuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
