# Generated by Django 5.0.2 on 2024-02-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_delete_product_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomeUser",
        ),
    ]
